wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: CONVLSTM
dataset:
  desc: null
  value: SKIPPD
epochs:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708364311.006605
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
